# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-20 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20190920_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 9, 20, 7, 10, 19, 399976, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
