# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-20 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20190920_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='username',
            field=models.TextField(default=datetime.datetime(2019, 9, 20, 13, 37, 23, 426689, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userimages',
            name='img',
            field=models.ImageField(upload_to=b''),
        ),
    ]
